steps:
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]
  dir: "/workspace/myapp"  # Specify the correct directory where package.json is located

- name: "gcr.io/cloud-builders/npm"
  args: ["test"]
  dir: "/workspace/myapp/tests"  # Make sure to use the same directory for testing

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: "/workspace/myapp"  # Use the same directory for deploying

# Add other steps as needed